/*
 * Gurjit Singh
 * Monday September 30th - 2019
 * This program displays a soccer multiple choice quiz
 */

/**
 *
 * @author gusin5788
 */
import java.awt.Color;  // Import for colour select for lblTwentyfirst

public class frmmultiplechoicequiz extends javax.swing.JFrame {

    /**
     * Creates new form frmmultiplechoicequiz
     */
    public frmmultiplechoicequiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFirst = new javax.swing.JPanel();
        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblThird = new javax.swing.JLabel();
        lblFourth = new javax.swing.JLabel();
        lblFifth = new javax.swing.JLabel();
        lblSixth = new javax.swing.JLabel();
        lblSeventh = new javax.swing.JLabel();
        lblEighth = new javax.swing.JLabel();
        lblNinth = new javax.swing.JLabel();
        lblTenth = new javax.swing.JLabel();
        lblEleventh = new javax.swing.JLabel();
        lblTwelfth = new javax.swing.JLabel();
        lblThirteenth = new javax.swing.JLabel();
        lblFourteenth = new javax.swing.JLabel();
        lblFifteenth = new javax.swing.JLabel();
        lblSixteenth = new javax.swing.JLabel();
        lblSeventeenth = new javax.swing.JLabel();
        lblEighteenth = new javax.swing.JLabel();
        lblNineteenth = new javax.swing.JLabel();
        lblTwentieth = new javax.swing.JLabel();
        lblTwentyfirst = new javax.swing.JLabel();
        lblTwentysecond = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnSecond = new javax.swing.JButton();
        btnThird = new javax.swing.JButton();
        btnFourth = new javax.swing.JButton();
        btnFifth = new javax.swing.JButton();
        btnSixth = new javax.swing.JButton();
        btnSeventh = new javax.swing.JButton();
        btnEighth = new javax.swing.JButton();
        btnNinth = new javax.swing.JButton();
        btnTenth = new javax.swing.JButton();
        btnEleventh = new javax.swing.JButton();
        btnTwelfth = new javax.swing.JButton();
        btnThirteenth = new javax.swing.JButton();
        btnFourteenth = new javax.swing.JButton();
        btnFifteenth = new javax.swing.JButton();
        btnSixteenth = new javax.swing.JButton();
        btnSeventeenth = new javax.swing.JButton();
        btnEighteenth = new javax.swing.JButton();
        btnNineteenth = new javax.swing.JButton();
        btnTwentieth = new javax.swing.JButton();
        btnTwentyfirst = new javax.swing.JButton();
        btnTwentysecond = new javax.swing.JButton();
        btnTwentythird = new javax.swing.JButton();
        btnTwentyfourth = new javax.swing.JButton();
        btnTwentyfifth = new javax.swing.JButton();
        btnTwentysixth = new javax.swing.JButton();
        btnTwentyseventh = new javax.swing.JButton();
        btnTwentyeighth = new javax.swing.JButton();
        btnTwentyninth = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFirst.setBackground(new java.awt.Color(153, 153, 255));

        lblFirst.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        lblFirst.setForeground(new java.awt.Color(255, 255, 255));
        lblFirst.setText("Soccer Quiz");

        lblSecond.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        lblSecond.setForeground(new java.awt.Color(255, 255, 255));
        lblSecond.setText("Answer each multiple choice question below");

        lblThird.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblThird.setForeground(new java.awt.Color(255, 255, 255));
        lblThird.setText("Question 1: Which club has won the second most honours among football clubs in Italy?");

        lblFourth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblFourth.setForeground(new java.awt.Color(255, 255, 255));
        lblFourth.setText("Question 2: In which continent were the soccer balls made from pig bladders during the middle ages?");

        lblFifth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblFifth.setForeground(new java.awt.Color(255, 255, 255));
        lblFifth.setText("Question 3: Which country has won the most world cups?");

        lblSixth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblSixth.setForeground(new java.awt.Color(255, 255, 255));
        lblSixth.setText("Question 4: Which country invented soccer?");

        lblSeventh.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblSeventh.setForeground(new java.awt.Color(255, 255, 255));
        lblSeventh.setText("Question 5: Who has scored the most goals in soccer history?");

        lblEighth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblEighth.setForeground(new java.awt.Color(255, 255, 255));
        lblEighth.setText("Question 6: Who won the Fifa World Player of the Year Award in 2004 and 2005?");

        lblNinth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblNinth.setForeground(new java.awt.Color(255, 255, 255));
        lblNinth.setText("Question 7: In what year will the world cup take place in Canada, USA, and Mexico?");

        lblTenth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblTenth.setForeground(new java.awt.Color(255, 255, 255));
        lblTenth.setText("Total Correct:");

        lblEleventh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emb_0010.png"))); // NOI18N

        lblTwelfth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblTwelfth.setForeground(new java.awt.Color(255, 255, 255));

        lblThirteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblThirteenth.setForeground(new java.awt.Color(255, 255, 255));

        lblFourteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblFourteenth.setForeground(new java.awt.Color(255, 255, 255));

        lblFifteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblFifteenth.setForeground(new java.awt.Color(255, 255, 255));

        lblSixteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblSixteenth.setForeground(new java.awt.Color(255, 255, 255));

        lblSeventeenth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblSeventeenth.setForeground(new java.awt.Color(255, 255, 255));

        lblEighteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblEighteenth.setForeground(new java.awt.Color(255, 255, 255));

        lblNineteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblNineteenth.setForeground(new java.awt.Color(255, 255, 255));

        lblTwentieth.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblTwentieth.setForeground(new java.awt.Color(255, 255, 255));
        lblTwentieth.setText("Marks:");

        lblTwentyfirst.setBackground(new java.awt.Color(255, 255, 255));
        lblTwentyfirst.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblTwentyfirst.setForeground(new java.awt.Color(255, 255, 255));

        lblTwentysecond.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblTwentysecond.setForeground(new java.awt.Color(255, 255, 255));

        btnFirst.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnFirst.setText("A.S. Roma ");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnSecond.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnSecond.setText("S.S.C. Napoli");
        btnSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecondActionPerformed(evt);
            }
        });

        btnThird.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnThird.setText("Ac Milan");
        btnThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirdActionPerformed(evt);
            }
        });

        btnFourth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnFourth.setText("ACF Fiorentina");
        btnFourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourthActionPerformed(evt);
            }
        });

        btnFifth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnFifth.setText("Europe");
        btnFifth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFifthActionPerformed(evt);
            }
        });

        btnSixth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnSixth.setText("Asia");
        btnSixth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixthActionPerformed(evt);
            }
        });

        btnSeventh.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnSeventh.setText("Oceania");
        btnSeventh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeventhActionPerformed(evt);
            }
        });

        btnEighth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnEighth.setText("South America");
        btnEighth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEighthActionPerformed(evt);
            }
        });

        btnNinth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnNinth.setText("Germany");
        btnNinth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNinthActionPerformed(evt);
            }
        });

        btnTenth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTenth.setText("Brazil");
        btnTenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenthActionPerformed(evt);
            }
        });

        btnEleventh.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnEleventh.setText("Italy");
        btnEleventh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleventhActionPerformed(evt);
            }
        });

        btnTwelfth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwelfth.setText("Argentina");
        btnTwelfth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwelfthActionPerformed(evt);
            }
        });

        btnThirteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnThirteenth.setText("Spain");
        btnThirteenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirteenthActionPerformed(evt);
            }
        });

        btnFourteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnFourteenth.setText("Uruguay");
        btnFourteenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourteenthActionPerformed(evt);
            }
        });

        btnFifteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnFifteenth.setText("France");
        btnFifteenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFifteenthActionPerformed(evt);
            }
        });

        btnSixteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnSixteenth.setText("England");
        btnSixteenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixteenthActionPerformed(evt);
            }
        });

        btnSeventeenth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnSeventeenth.setText("Romario");
        btnSeventeenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeventeenthActionPerformed(evt);
            }
        });

        btnEighteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnEighteenth.setText("Pele");
        btnEighteenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEighteenthActionPerformed(evt);
            }
        });

        btnNineteenth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnNineteenth.setText("Arthur Friedenreich");
        btnNineteenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineteenthActionPerformed(evt);
            }
        });

        btnTwentieth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentieth.setText("Josef Bican");
        btnTwentieth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentiethActionPerformed(evt);
            }
        });

        btnTwentyfirst.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentyfirst.setText("Ronaldinho");
        btnTwentyfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentyfirstActionPerformed(evt);
            }
        });

        btnTwentysecond.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentysecond.setText("Lionel Messi");
        btnTwentysecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentysecondActionPerformed(evt);
            }
        });

        btnTwentythird.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentythird.setText("Cristiano Ronaldo");
        btnTwentythird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentythirdActionPerformed(evt);
            }
        });

        btnTwentyfourth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentyfourth.setText("David Villa");
        btnTwentyfourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentyfourthActionPerformed(evt);
            }
        });

        btnTwentyfifth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentyfifth.setText("2022");
        btnTwentyfifth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentyfifthActionPerformed(evt);
            }
        });

        btnTwentysixth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentysixth.setText("2026");
        btnTwentysixth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentysixthActionPerformed(evt);
            }
        });

        btnTwentyseventh.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentyseventh.setText("2030");
        btnTwentyseventh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentyseventhActionPerformed(evt);
            }
        });

        btnTwentyeighth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentyeighth.setText("2034");
        btnTwentyeighth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentyeighthActionPerformed(evt);
            }
        });

        btnTwentyninth.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnTwentyninth.setText("Calculate");
        btnTwentyninth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwentyninthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFirstLayout = new javax.swing.GroupLayout(pnlFirst);
        pnlFirst.setLayout(pnlFirstLayout);
        pnlFirstLayout.setHorizontalGroup(
            pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirstLayout.createSequentialGroup()
                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFirstLayout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(lblFirst))
                    .addGroup(pnlFirstLayout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(lblSecond))
                    .addGroup(pnlFirstLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnTwentyfifth)
                        .addGap(117, 117, 117)
                        .addComponent(btnTwentysixth)
                        .addGap(98, 98, 98)
                        .addComponent(btnTwentyseventh)
                        .addGap(122, 122, 122)
                        .addComponent(btnTwentyeighth))
                    .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlFirstLayout.createSequentialGroup()
                            .addComponent(lblNinth)
                            .addGap(290, 290, 290)
                            .addComponent(lblTwentyfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14))
                        .addGroup(pnlFirstLayout.createSequentialGroup()
                            .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFirstLayout.createSequentialGroup()
                                    .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlFirstLayout.createSequentialGroup()
                                            .addGap(190, 190, 190)
                                            .addComponent(btnFirst)
                                            .addGap(57, 57, 57)
                                            .addComponent(btnSecond)
                                            .addGap(53, 53, 53)
                                            .addComponent(btnThird)
                                            .addGap(49, 49, 49)
                                            .addComponent(btnFourth))
                                        .addGroup(pnlFirstLayout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblFourth)
                                                .addComponent(lblThird)
                                                .addGroup(pnlFirstLayout.createSequentialGroup()
                                                    .addGap(160, 160, 160)
                                                    .addComponent(btnFifth)
                                                    .addGap(101, 101, 101)
                                                    .addComponent(btnSixth)
                                                    .addGap(89, 89, 89)
                                                    .addComponent(btnSeventh)
                                                    .addGap(47, 47, 47)
                                                    .addComponent(btnEighth))))
                                        .addGroup(pnlFirstLayout.createSequentialGroup()
                                            .addGap(47, 47, 47)
                                            .addComponent(lblFifth))
                                        .addGroup(pnlFirstLayout.createSequentialGroup()
                                            .addGap(191, 191, 191)
                                            .addComponent(btnNinth)
                                            .addGap(87, 87, 87)
                                            .addComponent(btnTenth, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(98, 98, 98)
                                            .addComponent(btnEleventh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61)
                                            .addComponent(btnTwelfth)))
                                    .addGap(33, 33, 33))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFirstLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSixth)
                                        .addGroup(pnlFirstLayout.createSequentialGroup()
                                            .addGap(153, 153, 153)
                                            .addComponent(btnThirteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(89, 89, 89)
                                            .addComponent(btnFourteenth)
                                            .addGap(85, 85, 85)
                                            .addComponent(btnFifteenth)
                                            .addGap(71, 71, 71)
                                            .addComponent(btnSixteenth))
                                        .addComponent(lblSeventh)
                                        .addGroup(pnlFirstLayout.createSequentialGroup()
                                            .addGap(144, 144, 144)
                                            .addComponent(btnSeventeenth)
                                            .addGap(89, 89, 89)
                                            .addComponent(btnEighteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(51, 51, 51)
                                            .addComponent(btnNineteenth)
                                            .addGap(40, 40, 40)
                                            .addComponent(btnTwentieth))
                                        .addComponent(lblEighth)
                                        .addGroup(pnlFirstLayout.createSequentialGroup()
                                            .addGap(126, 126, 126)
                                            .addComponent(btnTwentyfirst)
                                            .addGap(67, 67, 67)
                                            .addComponent(btnTwentysecond)
                                            .addGap(37, 37, 37)
                                            .addComponent(btnTwentythird)
                                            .addGap(44, 44, 44)
                                            .addComponent(btnTwentyfourth)))
                                    .addGap(85, 85, 85)))
                            .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTwentieth)
                                .addGroup(pnlFirstLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTwelfth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFourteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblThirteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFifteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSixteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSeventeenth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEighteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEleventh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlFirstLayout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(lblTenth))
                                .addGroup(pnlFirstLayout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(btnTwentyninth))
                                .addGroup(pnlFirstLayout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTwentysecond, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNineteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        pnlFirstLayout.setVerticalGroup(
            pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirstLayout.createSequentialGroup()
                .addComponent(lblFirst)
                .addGap(6, 6, 6)
                .addComponent(lblSecond)
                .addGap(4, 4, 4)
                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFirstLayout.createSequentialGroup()
                        .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFirstLayout.createSequentialGroup()
                                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFirstLayout.createSequentialGroup()
                                        .addComponent(lblTenth)
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFirstLayout.createSequentialGroup()
                                        .addComponent(lblThird)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFirst)
                                    .addComponent(btnSecond)
                                    .addComponent(btnThird)
                                    .addComponent(btnFourth)
                                    .addGroup(pnlFirstLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnTwentyninth)))
                                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlFirstLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lblFourth)
                                        .addGap(14, 14, 14)
                                        .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnFifth)
                                            .addComponent(btnSixth)
                                            .addComponent(btnSeventh)
                                            .addComponent(btnEighth))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblFifth)
                                        .addGap(11, 11, 11)
                                        .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNinth)
                                            .addComponent(btnTenth)
                                            .addComponent(btnEleventh)
                                            .addComponent(btnTwelfth)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFirstLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(lblNineteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTwentysecond, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlFirstLayout.createSequentialGroup()
                                .addComponent(lblTwentieth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblThirteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(lblTwelfth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(lblFourteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(lblSixth)
                        .addGap(11, 11, 11)
                        .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFirstLayout.createSequentialGroup()
                                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThirteenth)
                                    .addComponent(btnFourteenth)
                                    .addComponent(btnFifteenth)
                                    .addComponent(btnSixteenth))
                                .addGap(18, 18, 18)
                                .addComponent(lblSeventh))
                            .addComponent(lblFifteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFirstLayout.createSequentialGroup()
                                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSeventeenth)
                                    .addComponent(btnEighteenth)
                                    .addComponent(btnNineteenth)
                                    .addComponent(btnTwentieth))
                                .addGap(18, 18, 18)
                                .addComponent(lblEighth)
                                .addGap(11, 11, 11)
                                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTwentyfirst)
                                    .addComponent(btnTwentysecond)
                                    .addComponent(btnTwentythird)
                                    .addComponent(btnTwentyfourth)))
                            .addGroup(pnlFirstLayout.createSequentialGroup()
                                .addComponent(lblSixteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(lblSeventeenth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlFirstLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lblEleventh)))
                .addGap(5, 5, 5)
                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNinth)
                    .addComponent(lblTwentyfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEighteenth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTwentyfifth)
                    .addComponent(btnTwentysixth)
                    .addComponent(btnTwentyseventh)
                    .addComponent(btnTwentyeighth))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFirst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnFifthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFifthActionPerformed
        lblTwelfth.setText ("1");                                               // Start of button codes for first question
    }//GEN-LAST:event_btnFifthActionPerformed

    private void btnSixthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixthActionPerformed
        lblTwelfth.setText ("0");
    }//GEN-LAST:event_btnSixthActionPerformed

    private void btnSeventhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeventhActionPerformed
        lblTwelfth.setText ("0");
    }//GEN-LAST:event_btnSeventhActionPerformed

    private void btnEighthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEighthActionPerformed
        lblTwelfth.setText ("0");                                               // End of button codes for first question
    }//GEN-LAST:event_btnEighthActionPerformed
    
    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        lblThirteenth.setText ("0");                                            // Start of button codes for second question
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecondActionPerformed
        lblThirteenth.setText ("0");
    }//GEN-LAST:event_btnSecondActionPerformed

    private void btnThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirdActionPerformed
        lblThirteenth.setText ("1");
    }//GEN-LAST:event_btnThirdActionPerformed

    private void btnFourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourthActionPerformed
        lblThirteenth.setText ("0");                                            // End of button codes for second question
    }//GEN-LAST:event_btnFourthActionPerformed
    
    private void btnNinthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNinthActionPerformed
        lblFourteenth.setText ("0");                                            // Start of button codes for third questtion
    }//GEN-LAST:event_btnNinthActionPerformed

    private void btnTenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenthActionPerformed
        lblFourteenth.setText ("1");
    }//GEN-LAST:event_btnTenthActionPerformed

    private void btnEleventhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleventhActionPerformed
        lblFourteenth.setText ("0");
    }//GEN-LAST:event_btnEleventhActionPerformed

    private void btnTwelfthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwelfthActionPerformed
        lblFourteenth.setText ("0");                                            // End of button codes for third question
    }//GEN-LAST:event_btnTwelfthActionPerformed
    
    private void btnThirteenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirteenthActionPerformed
        lblFifteenth.setText ("0");                                             // Start of button codes for fourth question
    }//GEN-LAST:event_btnThirteenthActionPerformed

    private void btnFourteenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourteenthActionPerformed
        lblFifteenth.setText ("0");
    }//GEN-LAST:event_btnFourteenthActionPerformed

    private void btnFifteenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFifteenthActionPerformed
        lblFifteenth.setText ("0");
    }//GEN-LAST:event_btnFifteenthActionPerformed

    private void btnSixteenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixteenthActionPerformed
        lblFifteenth.setText ("1");                                             // End of button codes for fourth question
    }//GEN-LAST:event_btnSixteenthActionPerformed
    
    private void btnSeventeenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeventeenthActionPerformed
        lblSixteenth.setText ("0");                                             // Start of button codes for fifth question
    }//GEN-LAST:event_btnSeventeenthActionPerformed

    private void btnEighteenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEighteenthActionPerformed
        lblSixteenth.setText ("0");
    }//GEN-LAST:event_btnEighteenthActionPerformed

    private void btnNineteenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineteenthActionPerformed
        lblSixteenth.setText ("1");
    }//GEN-LAST:event_btnNineteenthActionPerformed

    private void btnTwentiethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentiethActionPerformed
        lblSixteenth.setText ("0");                                             // End of button codes for fifth question
    }//GEN-LAST:event_btnTwentiethActionPerformed
    
    private void btnTwentyfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentyfirstActionPerformed
        lblSeventeenth.setText ("1");                                           // Start of button codes for sixth question
    }//GEN-LAST:event_btnTwentyfirstActionPerformed

    private void btnTwentysecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentysecondActionPerformed
        lblSeventeenth.setText ("0");
    }//GEN-LAST:event_btnTwentysecondActionPerformed

    private void btnTwentythirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentythirdActionPerformed
        lblSeventeenth.setText ("0");
    }//GEN-LAST:event_btnTwentythirdActionPerformed

    private void btnTwentyfourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentyfourthActionPerformed
        lblSeventeenth.setText ("0");                                           // End of button codes for sixth question
    }//GEN-LAST:event_btnTwentyfourthActionPerformed
    
    private void btnTwentyfifthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentyfifthActionPerformed
        lblEighteenth.setText ("0");                                            // Start of button codes for seventh question
    }//GEN-LAST:event_btnTwentyfifthActionPerformed

    private void btnTwentysixthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentysixthActionPerformed
        lblEighteenth.setText ("1");
    }//GEN-LAST:event_btnTwentysixthActionPerformed

    private void btnTwentyseventhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentyseventhActionPerformed
        lblEighteenth.setText ("0");
    }//GEN-LAST:event_btnTwentyseventhActionPerformed

    private void btnTwentyeighthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentyeighthActionPerformed
        lblEighteenth.setText ("0");                                            // End of button codes for seventh question
    }//GEN-LAST:event_btnTwentyeighthActionPerformed
    
    private void btnTwentyninthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwentyninthActionPerformed
        int one = Integer.parseInt(lblTwelfth.getText());
        int two = Integer.parseInt(lblThirteenth.getText());
        int three = Integer.parseInt(lblFourteenth.getText());
        int four = Integer.parseInt(lblFifteenth.getText());
        int five = Integer.parseInt(lblSixteenth.getText());
        int six = Integer.parseInt(lblSeventeenth.getText());
        int seven = Integer.parseInt(lblEighteenth.getText()); // Line 763 to 769 are integers that equal the values of the marks' labels
        
        int totalcorrect = one + two + three + four + five + six + seven;
        lblNineteenth.setText("" + totalcorrect); // This displays the total number of correct answers
        double percentage = (one + two + three + four + five + six + seven) * 14.2857142857; // 7
        percentage = percentage * 10;
        percentage = Math.round(percentage); 
        percentage = percentage / 10; // Line 774 to 776 is the percentage round up
        lblTwentysecond.setText( percentage + "%"); // This displays the percentage
        
        if ((totalcorrect >= 0)&&(totalcorrect <=4)) {
            lblTwentyfirst.setText("  Try Harder!"); // Final statement regarding the total number of correct answers
            lblTwentyfirst.setBackground(Color.RED);
            lblTwentyfirst.setForeground(Color.WHITE);
            lblTwentyfirst.setOpaque(true);
        }
        if ((totalcorrect >=5)&&(totalcorrect <=7)) {
            lblTwentyfirst.setText("   Good Job!"); // Final statement regarding the total number of correct answers
            lblTwentyfirst.setBackground(Color.GREEN);
            lblTwentyfirst.setForeground(Color.BLACK);
            lblTwentyfirst.setOpaque(true);
        }
    }//GEN-LAST:event_btnTwentyninthActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmultiplechoicequiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmultiplechoicequiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmultiplechoicequiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmultiplechoicequiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmultiplechoicequiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEighteenth;
    private javax.swing.JButton btnEighth;
    private javax.swing.JButton btnEleventh;
    private javax.swing.JButton btnFifteenth;
    private javax.swing.JButton btnFifth;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnFourteenth;
    private javax.swing.JButton btnFourth;
    private javax.swing.JButton btnNineteenth;
    private javax.swing.JButton btnNinth;
    private javax.swing.JButton btnSecond;
    private javax.swing.JButton btnSeventeenth;
    private javax.swing.JButton btnSeventh;
    private javax.swing.JButton btnSixteenth;
    private javax.swing.JButton btnSixth;
    private javax.swing.JButton btnTenth;
    private javax.swing.JButton btnThird;
    private javax.swing.JButton btnThirteenth;
    private javax.swing.JButton btnTwelfth;
    private javax.swing.JButton btnTwentieth;
    private javax.swing.JButton btnTwentyeighth;
    private javax.swing.JButton btnTwentyfifth;
    private javax.swing.JButton btnTwentyfirst;
    private javax.swing.JButton btnTwentyfourth;
    private javax.swing.JButton btnTwentyninth;
    private javax.swing.JButton btnTwentysecond;
    private javax.swing.JButton btnTwentyseventh;
    private javax.swing.JButton btnTwentysixth;
    private javax.swing.JButton btnTwentythird;
    private javax.swing.JLabel lblEighteenth;
    private javax.swing.JLabel lblEighth;
    private javax.swing.JLabel lblEleventh;
    private javax.swing.JLabel lblFifteenth;
    private javax.swing.JLabel lblFifth;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFourteenth;
    private javax.swing.JLabel lblFourth;
    private javax.swing.JLabel lblNineteenth;
    private javax.swing.JLabel lblNinth;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblSeventeenth;
    private javax.swing.JLabel lblSeventh;
    private javax.swing.JLabel lblSixteenth;
    private javax.swing.JLabel lblSixth;
    private javax.swing.JLabel lblTenth;
    private javax.swing.JLabel lblThird;
    private javax.swing.JLabel lblThirteenth;
    private javax.swing.JLabel lblTwelfth;
    private javax.swing.JLabel lblTwentieth;
    private javax.swing.JLabel lblTwentyfirst;
    private javax.swing.JLabel lblTwentysecond;
    private javax.swing.JPanel pnlFirst;
    // End of variables declaration//GEN-END:variables
}
